Replace JitPack w/ On-Prem Maven Repository
Stack8/github-zenhub-sdk pull request #9
Opened 2024-12-03 20:47 UTC by justin-sadakhom

2024-12-06 17:41 UTC, justin-sadakhom commented
note: I made a mistake committing the gradle account creds to version control, but I've deleted that account to ensure security

2024-12-20 19:04 UTC, arotondo commented on build.gradle.kts
> +            url = uri("https://repository.goziro.com/repository/github-zenhub-sdk/")
Same as the other PR, how will this scale?

2024-12-20 19:15 UTC, justin-sadakhom commented on build.gradle.kts
> +            url = uri("https://repository.goziro.com/repository/github-zenhub-sdk/")
I think I had a mix up here. The repository itself should be "library" or some other name to represent all of our shared libraries. Then the artifact id will be github-zenhub-sdk. This way we can upload multiple artifacts to a repository and that's how it scales.

Will look into this.

2024-12-20 21:29 UTC, justin-sadakhom commented on build.gradle.kts
> +            url = uri("https://repository.goziro.com/repository/github-zenhub-sdk/")
just tested it and it works, we can have multiple artifacts underneath the same repo

2024-12-23 04:15 UTC, arotondo commented on build.gradle.kts
> +            url = uri("https://repository.goziro.com/repository/github-zenhub-sdk/")
k, gotcha... how about we call it "engineering-team" or "engineering"?

2024-12-23 04:23 UTC, arotondo commented on build.gradle.kts
> +if (project.hasProperty("snapshot")) {
nit: There should be a way for us to automate this so that we can just call publish. I am pretty we do some `git --describe` calls in smacs to achieve this. Anyway, this would be more of a nice to have, not a blocker. Wrote a chore #18593 to look into this in the new year.

2024-12-23 04:36 UTC, arotondo commented on build.gradle.kts
> +var currentVersion = "1.8.0"
If I am not mistaken, we have a few projects now whereby we use a `version.txt` to achieve this (including smacs - though probably not a good source of inspiration cause its more complicated there, but there are other projects where it is super simple).

Honestly, I think we should leverage `gradle.properties` at the project level for this, but that is another story (need a spike cause I think seb overrides it - #18595). 

For now, at the least, we should try to keep it consistent so that when we jump from project to project, we know exactly where to find the version, one less thing to translate. I wrote a #18594 for it, we can tackle it in the new year.

2024-12-23 04:58 UTC, arotondo commented on build.gradle.kts
> +            url = uri("https://repository.goziro.com/repository/stacks/")
So once we rename it to `engineering` (or `engineering-team` as commented in other PR), then this would be "https://repository.goziro.com/repository/engineering" right?

2024-12-23 05:15 UTC, arotondo requested changes
Good work! Made a couple nit comments w/ some f/u stories. And there is one action item to rename `stacks` to `engineering` or `engineering-team` (I'm good w/ either or), unless you have good reasons to keep `stacks`. 

Moving this to merge-ready!

2024-12-23 05:47 UTC, arotondo commented on build.gradle.kts
> +var currentVersion = "1.8.0"
Also, I am realizing that we will probably want snapshot to also work by branch and not just version 🤔 ... For example, if we are working on two separate feature branches for the same release, we will end up publishing to the same `<version>-SNAPSHOT`. We'd probably want something like `<branch>-SNAPSHOT` or `<branch>-<version>-SNAPSHOT` 🤔 I will reference this comment from the version.txt story so we can give this some more thought then.

2024-12-23 14:29 UTC, justin-sadakhom commented on build.gradle.kts
> +var currentVersion = "1.8.0"
good point about needing snapshots by branch and thanks for the followup stories

2024-12-23 14:41 UTC, merged